Graham Data Redesigning

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("CarolinaPmDataUTF_8.csv")

In [3]:
df.dtypes

State                                    object
State Code                              float64
Year                                    float64
Year Code                               float64
Fine Particulate Matter (µg/m≥)         float64
Fine Particulate Matter (µg/m≥) Code    float64
Avg Fine Particulate Matter (µg/m≥)     float64
dtype: object

In [5]:
df[["State", "Year", "Fine Particulate Matter (µg/m≥)", "Avg Fine Particulate Matter (µg/m≥)"]][0:297]

,State,Year,Fine Particulate Matter (µg/m≥),Avg Fine Particulate Matter (µg/m≥)
0,North Carolina,2003.0,3.0,2.88
1,North Carolina,2003.0,4.0,4.00
2,North Carolina,2003.0,5.0,5.02
3,North Carolina,2003.0,6.0,5.95
4,North Carolina,2003.0,7.0,7.02
...,...,...,...,...
292,North Carolina,2011.0,26.0,25.93
293,North Carolina,2011.0,27.0,27.30
294,North Carolina,2011.0,28.0,27.74
295,North Carolina,2011.0,NaN,12.36
296,North Carolina,NaN,NaN,12.97

In [13]:
Data1 = df[["State", "Year", "Fine Particulate Matter (µg/m≥)", "Avg Fine Particulate Matter (µg/m≥)"][0:297]].copy()

In [14]:
Data1

,State,Year,Fine Particulate Matter (µg/m≥),Avg Fine Particulate Matter (µg/m≥)
0,North Carolina,2003.0,3.0,2.88
1,North Carolina,2003.0,4.0,4.00
2,North Carolina,2003.0,5.0,5.02
3,North Carolina,2003.0,6.0,5.95
4,North Carolina,2003.0,7.0,7.02
...,...,...,...,...
293,North Carolina,2011.0,27.0,27.30
294,North Carolina,2011.0,28.0,27.74
295,North Carolina,2011.0,NaN,12.36
296,North Carolina,NaN,NaN,12.97
297,NaN,NaN,NaN,12.97